//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub use super::product_db::Entity as ProductDb;
pub use super::supermarket_price::Entity as SupermarketPrice;
pub use super::supermarkets::Entity as Supermarkets;
