//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "product_db")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub product_id: i32,
    pub product_title: String,
    pub product_variety: Option<String>,
    pub product_brand: Option<String>,
    pub image_url: Option<String>,
    pub barcode: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub size: Option<f32>,
    pub unit: Option<String>,
    pub quantity: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
